# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_bean', '0002_auto_20170817_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('water', models.FloatField()),
                ('foam', models.FloatField()),
                ('milk', models.BooleanField(default=False)),
                ('shots', models.PositiveIntegerField()),
                ('extra_instructions', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_bean.Bean')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_bean.Powder')),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_bean.Roast')),
                ('syrup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_bean.Syrup')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
