# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_bean', '0009_auto_20170820_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='extra_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
