# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_bean', '0011_auto_20170821_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
