# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_bean', '0012_auto_20170821_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='powder',
            field=models.ManyToManyField(blank=True, to='coffee_bean.Powder'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='syrup',
            field=models.ManyToManyField(blank=True, to='coffee_bean.Syrup'),
        ),
    ]
