# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_bean', '0013_auto_20170822_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Apt',
            new_name='apt_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='extra_details',
            new_name='extra_instructions',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='flat',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='building',
            new_name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='avenue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='building_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
